### ISSUE TITLE
文章列表页面没有分页功能

### ISSUE THREAD

**Issue by scmiot** [xioyito/NewBee#1]
很喜欢作者这个主题，刚才测试了下，

1、发现列表页面没有分页功能，请问下后期是否会增加分页功能？

2、页面切换loging的比较慢，主要是以下几个请求，几乎都会超过1秒，联通500MB宽带情况下：
https://api.ip.sb/jsonip?callback=cb_1g7m0i2&t=16575224394
https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0
这个是否可以优化？

**Comment by xioyito** [comment]
> 很喜欢作者这个主题，刚才测试了下，
> 
> 1、发现列表页面没有分页功能，请问下后期是否会增加分页功能？
> 
> 2、页面切换loging的比较慢，主要是以下几个请求，几乎都会超过1秒，联通500MB宽带情况下： https://api.ip.sb/jsonip?callback=cb_1g7m0i2&t=16575224394 https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0 这个是否可以优化？

非常感谢对 NewBee 主题的支持。
1，列表页面分页功能之后可能会有，或者是以另一种形式呈现。
2、这几个拖慢页面加载的请求之前也注意到过，但是因为本身我自己也还在学习当中，由于一些技术问题，暂时还没办法解决。后期的话，肯定是会进行优化的。

**Comment by scmiot** [comment]
谢谢回复，我自己先尝试下看看哪个CDN联通访问会快些，谢谢！
