### ISSUE TITLE
图片无法更改、汉化不彻底、页面丢失

### ISSUE THREAD

**Issue by ITYuShi** [xioyito/NewBee#11]
hugo版本为0.105.0，并已按照readme中的步骤完成操作并可正常在本运行

1.我用自己的图片覆盖了该图片："根站点\themes\NewBee\static\images\author.jpeg""， 但依旧显示的默认原图
2.我更改了配置中的 defaultContentLanguage = "zh"，但页面顶部的home、posts等依旧是英文
3. 点入任意一篇文章，右边的作者栏，点击分类、标签，会显示：“抱歉，页面好像走丢了”

很喜欢作者的这个主题！但我对前端了解的不多，不清楚是我的操作问题还是该主题本身的bug

**Comment by xioyito** [comment]
感谢支持！
1、尝试浏览器 ctrl + shift + R 强制刷新。如果还不行，尝试关闭hugo server后再次开启，再刷新浏览器试试。
2、语言的配置请参考示例网站里的文章：”语言支持“。
3、已修复。

**Comment by xioyito** [comment]
@ITYuShi 感谢支持！
1、尝试浏览器 ctrl + shift + R 强制刷新。如果还不行，尝试关闭hugo server后再次开启，再刷新浏览器试试。
2、语言的配置请参考示例网站里的文章：”语言支持“。
3、已修复。

**Comment by ITYuShi** [comment]
该项目的README文件，前面所展示的示例网站  https://xioyito.top/  无法点开，显示404页面

**Comment by ITYuShi** [comment]
感谢解惑，问题已全部解决！
