### ISSUE TITLE
一点样式问题与建议

### ISSUE THREAD

**Issue by ITYuShi** [xioyito/NewBee#12]
作者你好，我在使用过程中遇到了一点关于主题样式的问题

1.  在暗模式下，markdown的**行类代码块**非常亮，几乎看不清
2. 使用该主题提供的**highlight**，在**暗模式**下，python代码段，导入库颜色非常暗，例如：import os  这段代码，os两个字的颜色非常暗

当然这并不太影响使用，可以采用加粗或你提供的note来代替行类样式，以及不使用highlight即可

除此之外还有一点小建议，不知道是否可行

因为hugo的核心理念就是将内容与代码逻辑分离，如果在文章内大量使用你或官方提供的shortcodes，这会大大降低文章的可移植性

而且许多markdown编辑器，如typora，并不支持hugo的语法，大量使用shortcodes，写起来也很难受

所以可不可以直接用主题样式代替markdown的原本渲染模式？

比如用你提供的默认note，代替接管markdown的行内代码块，highlight接管markdown的代码块，提供一个全局配置，供用户选择是否使用

我目前只是大致看了一下hugo的官方文档，并不清楚这种方案的可行性，如有不妥请忽略

**Comment by xioyito** [comment]
@ITYuShi 
1. 已修复
2. 已修复，若还有显示问题，请修改 syntax.css 或 syntax-dark.css 文件

谢谢你的建议，我已经做了相应的改动，具体请参考：https://xioyito.top/posts/%E5%86%85%E5%AE%B9%E7%AE%A1%E7%90%86/ 第6部分。

**Comment by ITYuShi** [comment]
引用与行内代码块的样式可以正常被主题替换，但highlight不能正常替换原本的markdown代码块样式

http://ityushi.cn/posts/go/file/

**Comment by ITYuShi** [comment]
还有能不能提供一个全局配置，可以默认使用暗主题？乃至可以关闭切换主题的按钮？感谢作者！

**Comment by xioyito** [comment]
> 引用与行内代码块的样式可以正常被主题替换，但highlight不能正常替换原本的markdown代码块样式
> 
> http://ityushi.cn/posts/go/file/

方便的话请把随便一段出错代码块的原 markdown 文本以及 config.toml 文件发我，谢谢。邮箱730056935@qq.com

**Comment by xioyito** [comment]
> 引用与行内代码块的样式可以正常被主题替换，但highlight不能正常替换原本的markdown代码块样式
> 
> http://ityushi.cn/posts/go/file/

尝试下载 .zip 文件后解压复制到 themes 目录以重新安装主题（不要用 git），网站 config.toml 里 highlight 配置部分的 lineNumbersInTable 参数请暂时保持为 true

**Comment by ITYuShi** [comment]
谢谢作者，已全部解决！

不过要尽善尽美的话，建议作者给主题加一个自动·清理缓存的功能，不然对前端、浏览器机制不熟悉的新手，用起来会很难受

因为很多配置更改了却没反应（得自己手动清理浏览器缓存才行）一般使用者是不会想这么多的，可能就觉得你这个主题有问题，然后就直接更换其它主题了，而不会过多专研文档（至少最开始我就是这样的）

我看到一篇文章，似乎有可行性：https://blog.csdn.net/diaojw090/article/details/90258852

**Comment by xioyito** [comment]
> 谢谢作者，已全部解决！
> 
> 不过要尽善尽美的话，建议作者给主题加一个自动·清理缓存的功能，不然对前端、浏览器机制不熟悉的新手，用起来会很难受
> 
> 因为很多配置更改了却没反应（得自己手动清理浏览器缓存才行）一般使用者是不会想这么多的，可能就觉得你这个主题有问题，然后就直接更换其它主题了，而不会过多专研文档（至少最开始我就是这样的）
> 
> 我看到一篇文章，似乎有可行性：https://blog.csdn.net/diaojw090/article/details/90258852

👌🏻
