### ISSUE TITLE
【建议】加个实现选项卡的 Shortcodes

### ISSUE THREAD

**Issue by SMWHff** [xioyito/NewBee#13]
选项卡样式参考：
https://vuepress-theme-hope.github.io/v1/md-enhance/zh/guide/tabs.html#

**Comment by xioyito** [comment]
@SMWHff 已更新，详见：<https://xioyito.top/posts/markdown%E6%89%A9%E5%B1%95%E8%AF%AD%E6%B3%95/>

**Comment by SMWHff** [comment]
Done
