### ISSUE TITLE
代码块显示错误

### ISSUE THREAD

**Issue by gzpeng233** [xioyito/NewBee#14]
代码块第一行添加close后，并未达到刷新为关闭状态的效果，反而是代码中多了一行"close"
我的源代码：
![pic1](https://user-images.githubusercontent.com/116292674/214517485-1616efd9-0b23-4f3e-96c6-5b47b1f63278.jpg)
我的设置：
![pic2](https://user-images.githubusercontent.com/116292674/214517460-b6a8c55c-d010-4f84-b299-dd5b31ab3fc0.jpg)
文档中描述：
![pic3](https://user-images.githubusercontent.com/116292674/214517518-c2e0fdf1-84ad-4a20-a139-3afd70751ee2.jpg)
最终实现效果：
![pic4](https://user-images.githubusercontent.com/116292674/214517538-3c414133-885d-4c8b-8f6e-82d99f4f6af4.jpg)

**Comment by xioyito** [comment]
@gzpeng233 尝试一下这篇文章第一个问题的解决办法：<https://xioyito.top/posts/%E9%81%BF%E5%9D%91%E6%8C%87%E5%8D%97/>

**Comment by gzpeng233** [comment]
未解决，强制刷新和重新开启网站都无法解决

**Comment by gzpeng233** [comment]
> @gzpeng233 尝试一下这篇文章第一个问题的解决办法：https://xioyito.top/posts/%E9%81%BF%E5%9D%91%E6%8C%87%E5%8D%97/

未解决，强制刷新和重新开启网站都无法解决

**Comment by gzpeng233** [comment]
@xioyito 未解决，强制刷新和重新开启网站都无法解决

**Comment by xioyito** [comment]
@gzpeng233 尝试重新下载主题安装。

**Comment by gzpeng233** [comment]
@xioyito 打扰了，我重新下载了v1.2.0版本的主题，确实没有效果

**Comment by xioyito** [comment]
方便的话麻烦把你网站源文件发我，我这边试试发自我的手机-------- 原始邮件 --------发件人： 葛震鹏 ***@***.***>日期： 2023年1月29日周日 14:19收件人： xioyito/NewBee ***@***.***>抄送： xioyito ***@***.***>, Mention ***@***.***>主    题： Re: [xioyito/NewBee] 代码块显示错误 (Issue #14)

@xioyito 打扰了，我重新下载了v1.2.0版本的主题，确实没有效果

**Comment by gzpeng233** [comment]
谢谢！问题解决了
从头开始做了一遍网站，发现没有问题
之后回过头再看原来的网站也没问题了，可能是和缓存有关（电脑小白）
抱歉了，Thanks！

**Comment by gzpeng233** [comment]
@xioyito 谢谢！问题解决了
从头开始做了一遍网站，发现没有问题
之后回过头再看原来的网站也没问题了，可能是和缓存有关（电脑小白）
抱歉了，Thanks！

**Comment by gzpeng233** [comment]
@xioyito 抱歉
zhe这是本地服务器：
![1](https://user-images.githubusercontent.com/116292674/215331222-6c078a46-f3ea-4d64-a743-4b4d358c9fb1.jpg)
这是上传后的样子：
![2](https://user-images.githubusercontent.com/116292674/215331247-4433842c-029e-4961-920c-b4ac2286d748.jpg)
为什么会这样子（凌乱）

**Comment by gzpeng233** [comment]
本地服务器渲染是正常的，刚开始处于闭合状态
我的网站却是显示 close

**Comment by xioyito** [comment]
你网站链接给我，我看看发自我的手机-------- 原始邮件 --------发件人： 葛震鹏 ***@***.***>日期： 2023年1月29日周日 22:03收件人： xioyito/NewBee ***@***.***>抄送： xioyito ***@***.***>, Mention ***@***.***>主    题： Re: [xioyito/NewBee] 代码块显示错误 (Issue #14)

@xioyito 抱歉

zhe这是本地服务器：



这是上传后的样子：



为什么会这样子（凌乱）

**Comment by gzpeng233** [comment]
@xioyito https://gzpeng233.github.io/posts/pid/

**Comment by xioyito** [comment]
我看到你网站里的js代码并不是最新的版本，可能是你上传文件到github上时出现了错误，请尝试把github上的文件都删了再重新上传。




去去去
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xioyito/NewBee"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月30日(星期一) 上午10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xioyito/NewBee] 代码块显示错误 (Issue #14)





 
@xioyito https://gzpeng233.github.io/posts/pid/

**Comment by gzpeng233** [comment]
抱歉
用的最新版本是指v1.2.0的版本，并不是master的最新版本，更换为master分支后不存在问题了

十分感谢！
