### ISSUE TITLE
第一次访问时加载太慢了

### ISSUE THREAD

**Issue by jackyzjk** [xioyito/NewBee#15]
为何现在第一次访问时加载辣么久，这个能否优化下，我用其他的主题都很快的，但架不住你的主题好看啊，所以大神能否给优化一下

**Comment by jackyzjk** [comment]
之前提交过一个类似的issue，当时你给解决了，但现在用了最新版的还是要加载很久，[你的网站](https://xioyito.top/)也是如此

**Comment by xioyito** [comment]
@jackyzjk 感谢支持！经排查是math-jax和mermaid引入外部js的原因，关于更新后这两个的新使用方法，请参考<https://xioyito.top/posts/markdown%E6%89%A9%E5%B1%95%E8%AF%AD%E6%B3%95/>。有问题请再反馈，谢谢。

**Comment by jackyzjk** [comment]
大神真给力，试了果然加载快了很多，3Q
