### ISSUE TITLE
如何才能隐藏最新编辑的文档不让它出现在主页的最新文章列表中

### ISSUE THREAD

**Issue by jackyzjk** [xioyito/NewBee#16]
我的情况是有些新建的文档需要在主页的最新文章列表中展示，但是有些是不需要展示在主页的，所以想请教一下，如何才能隐藏最新编辑的文档不让它出现在主页的最新文章列表中

**Comment by xioyito** [comment]
主题已更新，升级后在需要的文章的前置参数里设置hideFromHomePage为true即可。
