### ISSUE TITLE
运行Hugo server后报错“ERROR render of "taxonomy" failed:"，请问这是什么原因导致的？

### ISSUE THREAD

**Issue by Moondok** [xioyito/NewBee#17]
我按照示例站上面的步骤配置之后，首先是端口1313显示“no page found",之后我将‘theme='NewBee''添加在hugo.toml下再次运行hugo server,产生了下面的报错。
![](https://user-images.githubusercontent.com/83672574/253859010-0b5a84d9-b7d8-4765-b4c3-8de4b6bc61b3.jpg)

**Comment by Moondok** [comment]
我按照示例站上面的步骤配置之后，首先是端口1313显示“no page found",之后我将‘theme='NewBee''添加在hugo.toml下再次运行hugo server,产生了下面的报错。
![error](https://github.com/xioyito/NewBee/assets/83672574/0b5a84d9-b7d8-4765-b4c3-8de4b6bc61b3)

**Comment by xioyito** [comment]
请检查配置文件config.toml里的maxHomePostCount、maxPageRelatedCount和maxPageNewestCount参数是否已设置

**Comment by xioyito** [comment]
把配置文件config.toml重命名为hugo.toml，hugo官方好像把这个名字给修改了

**Comment by xioyito** [comment]
还有，端口不一定是1313，得看hugo server -D之后控制台输出的具体端口，例如：Web Server is available at http://localhost:55240/

**Comment by Moondok** [comment]
好的！感谢！

**Comment by Moondok** [comment]
好的，感谢
