### ISSUE TITLE
貌似是函数调用失败

### ISSUE THREAD

**Issue by db-root** [xioyito/NewBee#18]
你好，我克隆这个主题到本地之后使用hugo server启动时报错
PS G:\博客\boke> hugo server --buildDrafts
Start building sites … 
hugo v0.115.3-5c2e014a5150553a9fa4f9c1eb7dc4db89c0f1ab windows/amd64 BuildDate=2023-07-13T16:11:34Z VendorInfo=gohugoio

ERROR render of "section" failed: "G:\博客\boke\themes\NewBee\layouts\_default\about.html:10:19": execute of template failed: template: _default/about.html:10:19: executing "main" at <partial "widgets/zhuti-r.html" .>: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\zhuti-r.html:13:15": execute of template failed: template: partials/widgets/zhuti-r.html:13:15: executing "partials/widgets/zhuti-r.html" at <partial "widgets/other.html" .>: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\other.html:2:20": execute of template failed: template: partials/widgets/other.html:2:20: executing "partials/widgets/other.html" at <first .Site.Params.page.maxPageNewestCount .Site.RegularPages>: error calling first: both limit and seq must be provided
ERROR render of "taxonomy" failed: "G:\博客\boke\themes\NewBee\layouts\categories\terms.html:2:7": execute of template failed: template: categories/terms.html:2:7: executing "main" at <partial "widgets/taxoAndTerms.html" .>: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\taxoAndTerms.html:10:19": execute of template failed: template: partials/widgets/taxoAndTerms.html:10:19: executing "partials/widgets/taxoAndTerms.html" at <partial "widgets/zhuti-r.html" .>: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\zhuti-r.html:13:15": execute of template failed: template: partials/widgets/zhuti-r.html:13:15: executing "partials/widgets/zhuti-r.html" at <partial "widgets/other.html" .>: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\other.html:2:20": execute of template failed: template: partials/widgets/other.html:2:20: ets/taxoAndTerms.html" .>: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\taxoAndTerms.html:10:19": execute of template failed: template: partials/widgets/taxoAndTerms.html:10:19: executing "partials/widgets/taxoAndTerms.html" at <partial "widgets/zhuti-r.html" .>: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\zhuti-r.html:13:15": execute of template failed: template: partials/widgets/zhuti-r.html:13:15: executing "partials/widgets/zhuti-r.html" at <partial "widgets/other.html" .>: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\other.html:2:20": execute of template failed: template: partials/widgets/other.html:2:20: executing "partials/widgets/other.html" at <first .Site.Params.page.maxPageNewestCount .Site.RegularPages>: error calling first: both limit and seq must be provided
Built in 205 ms
Error: error building site: render: failed to render pages: render of "home" failed: "G:\博客\boke\themes\NewBee\layouts\index.html:16:29": execute of template failed: template: index.html:16:29: executing "main" at <first .Site.Params.page.maxHomePostCount .Site.RegularPages>: error calling first: both limit and seq must be provided

**Comment by xioyito** [comment]
把配置文件config.toml改成hugo.toml就行了，这个问题我正在修复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: db-root ***@***.***&gt;
发送时间: 2023年7月20日 22:34
收件人: xioyito/NewBee ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [xioyito/NewBee] 貌似是函数调用失败 (Issue #18)





 
你好，我克隆这个主题到本地之后使用hugo server启动时报错
 PS G:\博客\boke&gt; hugo server --buildDrafts
 Start building sites …
 hugo v0.115.3-5c2e014a5150553a9fa4f9c1eb7dc4db89c0f1ab windows/amd64 BuildDate=2023-07-13T16:11:34Z VendorInfo=gohugoio
 
ERROR render of "section" failed: "G:\博客\boke\themes\NewBee\layouts_default\about.html:10:19": execute of template failed: template: _default/about.html:10:19: executing "main" at <partial "widgets/zhuti-r.html" .&gt;: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\zhuti-r.html:13:15": execute of template failed: template: partials/widgets/zhuti-r.html:13:15: executing "partials/widgets/zhuti-r.html" at <partial "widgets/other.html" .&gt;: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\other.html:2:20": execute of template failed: template: partials/widgets/other.html:2:20: executing "partials/widgets/other.html" at <first .Site.Params.page.maxPageNewestCount .Site.RegularPages&gt;: error calling first: both limit and seq must be provided
 ERROR render of "taxonomy" failed: "G:\博客\boke\themes\NewBee\layouts\categories\terms.html:2:7": execute of template failed: template: categories/terms.html:2:7: executing "main" at <partial "widgets/taxoAndTerms.html" .&gt;: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\taxoAndTerms.html:10:19": execute of template failed: template: partials/widgets/taxoAndTerms.html:10:19: executing "partials/widgets/taxoAndTerms.html" at <partial "widgets/zhuti-r.html" .&gt;: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\zhuti-r.html:13:15": execute of template failed: template: partials/widgets/zhuti-r.html:13:15: executing "partials/widgets/zhuti-r.html" at <partial "widgets/other.html" .&gt;: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\other.html:2:20": execute of template failed: template: partials/widgets/other.html:2:20: ets/taxoAndTerms.html" .&gt;: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\taxoAndTerms.html:10:19": execute of template failed: template: partials/widgets/taxoAndTerms.html:10:19: executing "partials/widgets/taxoAndTerms.html" at <partial "widgets/zhuti-r.html" .&gt;: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\zhuti-r.html:13:15": execute of template failed: template: partials/widgets/zhuti-r.html:13:15: executing "partials/widgets/zhuti-r.html" at <partial "widgets/other.html" .&gt;: error calling partial: "G:\博客\boke\themes\NewBee\layouts\partials\widgets\other.html:2:20": execute of template failed: template: partials/widgets/other.html:2:20: executing "partials/widgets/other.html" at <first .Site.Params.page.maxPageNewestCount .Site.RegularPages&gt;: error calling first: both limit and seq must be provided
 Built in 205 ms
 Error: error building site: render: failed to render pages: render of "home" failed: "G:\博客\boke\themes\NewBee\layouts\index.html:16:29": execute of template failed: template: index.html:16:29: executing "main" at <first .Site.Params.page.maxHomePostCount .Site.RegularPages&gt;: error calling first: both limit and seq must be provided

**Comment by db-root** [comment]
我刚刚将themes\NewBee\config.toml改为了hugo.toml，但是还是这个样子，是我改的地方不对吗

**Comment by xioyito** [comment]
改你的网站根目录下的config，不是主题下的config



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: db-root ***@***.***&gt;
发送时间: 2023年7月20日 22:50
收件人: xioyito/NewBee ***@***.***&gt;
抄送: xioyito ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [xioyito/NewBee] 貌似是函数调用失败 (Issue #18)





 
我刚刚将themes\NewBee\config.toml改为了hugo.toml，但是还是这个样子，是我改的地方不对吗

**Comment by db-root** [comment]
![image](https://github.com/xioyito/NewBee/assets/90075706/616ba530-fb5d-4c9f-96f7-fa9f7f8f1bc0)
抱歉，这么晚了还提这个问题，但是我确实第一次接触这个工具，不太了解。
我这个根目录下的hugo.toml还是默认的文件，这个是不是需要做什么更改的

**Comment by xioyito** [comment]
没事，我也是在学习中，咱们共同进步，有任何建议欢迎提出。解决办法：用themes/NewBee/config-example/hugo.toml替换根目录下的hugo.toml就行，关于主题的更多信息可以访问xioyito.top
