### ISSUE TITLE
主题使用手机端微信自带浏览器首页首次打开会跳转色情或赌博网站

### ISSUE THREAD

**Issue by scmiot** [xioyito/NewBee#2]
#主题使用手机端微信自带浏览器首页首次打开会跳转色情或赌博网站，附件是跳转的截图，如果您这里无法重现，我可以email发您一段录屏视频。

![webwxgetmsgimg](https://user-images.githubusercontent.com/91941652/178361745-6e63bf1f-2a12-4488-b7fc-3addd092f24c.jpeg)

![截图 2022-07-12 05-58-28](https://user-images.githubusercontent.com/91941652/178365940-fa65e9c1-c755-47f4-a394-fc6b18c1fb46.png)

config中禁用访问量统计后不再出现色情网站跳转，建议禁用“不蒜子”。

**Comment by xioyito** [comment]
麻烦发下录屏，谢谢

**Comment by scmiot** [comment]
https://user-images.githubusercontent.com/91941652/178402235-43072373-075c-4cc2-8d32-6f5341f073ba.mp4

edge 或者 chrome 也可以重现，开启不蒜子统计，浏览器摄制成手机模式才可以。

**Comment by xioyito** [comment]
这边测试了下，网站上线后是不会出现sq网站的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xioyito/NewBee"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 凌晨5:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xioyito/NewBee] 主题使用手机端微信自带浏览器首页首次打开会跳转色情或赌博网站 (Issue #2)





 
主题使用手机端微信自带浏览器首页首次打开会跳转色情或赌博网站，附件是跳转的截图，如果您这里无法和重现，我可以email发您一段录屏视频。

**Comment by scmiot** [comment]
我也测试了线上的确没有跳转，但这个东西总觉得不舒服！

**Comment by xioyito** [comment]
&nbsp;
你再config里把visitor改成false就行，不会加载它的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xioyito/NewBee"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 中午12:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xioyito/NewBee] 主题使用手机端微信自带浏览器首页首次打开会跳转色情或赌博网站 (Issue #2)





 
我也测试了线上的确没有跳转，但这个东西总觉得不舒服！
