### ISSUE TITLE
How to activate toc?

### ISSUE THREAD

**Issue by teotenn** [xioyito/NewBee#21]
Hi, thank you for your wonderful theme, I really like it. I just cannot find out how to activate the table of contents. I can see in your site example that it appears in the bar at the right side, below the author's details. But I cannot make it appear for my posts. I would really appreciate help on this.

Thanks in advance.

**Comment by teotenn** [comment]
Sorry, I found the issue. It did not work for posts where title 1 is missing (`#`).

**Comment by xioyito** [comment]
> Sorry, I found the issue. It did not work for posts where title 1 is missing (`#`).

yes! the table of contents need the first post to appear. thanks for your support.
