### ISSUE TITLE
css样式部署到gitpage上发生失效问题

### ISSUE THREAD

**Issue by Moondok** [xioyito/NewBee#22]
您好，我在将您的Hugo模板部署到gitpage的时候发现里面的样式和图片全部丢失，只剩下静态html骨架了。
我的具体做法如下：
1.将config.toml config-advance.toml, hugo.toml三个文件中的BaseURL改为我的github io地址。
2.同步到远程仓库。
请问正确的做法应该是什么呢

**Comment by xioyito** [comment]
可能是同步仓库时出了问题，尝试删了仓库重新上传

**Comment by Moondok** [comment]
我重新拉下来最新的仓库试了一遍，发现同步上去之后还是不行。
我的做法是:
1. 把hugo.toml中的BaseURL换成了’https://xx.github.io/blog/‘ ，
2. 通过hugo -d xx/blog  输出静态网页到本地
3. push到github上github.io仓库的上面
结果如下图
![屏幕截图 2023-10-08 003806](https://github.com/xioyito/NewBee/assets/83672574/668bf894-d1ab-4dd4-9123-0d6b8585e826)

**Comment by xioyito** [comment]
生成的静态网页文件需要直接放在 https://xx.github.io/ 下，不要放在子目录 /blog 下

**Comment by Moondok** [comment]
okk现在可以了，谢谢！
