### ISSUE TITLE
【建议】希望 Markdown 的超链接语法支持新标签页打开

### ISSUE THREAD

**Issue by SMWHff** [xioyito/NewBee#25]
这个种标准格式只能当前页打开连接：
`[当前页超连接](http://www.example.com)`

**希望增加新标签页打开链接的语法：**
`[新标签页超链接](tab:http://www.example.com)`

---

参考文档：<a href="https://herman.bearblog.dev/markdown-cheatsheet/#links" target="_blank">Markdown cheatsheet | ᕕ( ᐛ )ᕗ Herman's blog</a>

**Comment by xioyito** [comment]
已更新

**Comment by SMWHff** [comment]
太棒了！谢谢^_^

**Comment by xioyito** [comment]
应该的
