### ISSUE TITLE
【BUG】以 `_` 开头的 `_custom.css` 样式文件上传到  GitHub Pages 网站无法被识别

### ISSUE THREAD

**Issue by SMWHff** [xioyito/NewBee#26]
以 “_” 开头的文件会报404错误
![image](https://github.com/xioyito/NewBee/assets/46310389/54bf618f-7845-4f4c-b572-c9111efd394b)

**我改成 “user_custom.css” 就正常了**
![image](https://github.com/xioyito/NewBee/assets/46310389/02fa49f2-b186-4b35-9ed2-92d206a4cd6b)

**Comment by SMWHff** [comment]
【补充】：缺少 `_custom.css` 样式文件会导致无法切换夜间模式

**Comment by xioyito** [comment]
冒昧问下您在地址栏访问css的目的是什么. 如果只是访问页面的话, 应该不会有问题

**Comment by SMWHff** [comment]
因为填在 `_custom.css` 里的样式在本地是生效的，上传到 GitHub Pages 网站后不生效

**Comment by xioyito** [comment]
_custom.css已更新为custom.css

**Comment by SMWHff** [comment]
太给力了！
