### ISSUE TITLE
网页左上角的文字logo未与配置中的baseURL关联

### ISSUE THREAD

**Issue by slske** [xioyito/NewBee#29]
如题

**Comment by slske** [comment]
强制刷新会一直显示加载，不知道是不是hugo的原因 。

**Comment by slske** [comment]
怪不得替换不了主页图，原来压根就不支持子目录啊。

**Comment by slske** [comment]
抱歉，我错了，是支持子目录的。

**Comment by slske** [comment]
![PixPin_2024-02-18_22-48-38](https://github.com/xioyito/NewBee/assets/48957981/a24f9448-7a9c-4d49-9802-a495f6bc0a6f)
好吧,没适配子目录的文件还挺多0.0

**Comment by xioyito** [comment]
看下你的目录结构

**Comment by slske** [comment]
slske.github.io/blog/
我就是将所有文件放在根目录下的一个文件夹里的

**Comment by xioyito** [comment]
直接放在根目录下, 不要放在根目录下的文件夹

**Comment by xioyito** [comment]
![屏幕截图 2024-02-20 220343](https://github.com/xioyito/NewBee/assets/59784211/fc68bb83-4805-4b5f-811e-1853b5ac989e)

**Comment by slske** [comment]
哈哈，好的。原来真没适配啊，问题不大，已经用笨办法解决了，就是明年可能会遇到更新麻烦。
非常感谢，打扰了。

**Comment by xioyito** [comment]
不客气, 感谢支持
