### ISSUE TITLE
【请教】

### ISSUE THREAD

**Issue by Bladeisme** [xioyito/NewBee#30]
要怎么把valine评论系统换成waline呀，修改了comments.html文件以及head.html部分的valine，这里不知道怎么改，直接替换成了

    {{ if .Site.Params.waline.enable }}
        <script src='https://cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js'></script>
    {{ end }}
    {{ if and (.Params.comments | default .Site.Params.enableComments) (eq hugo.Environment "production") }}
    {{ if or (in .Site.Params.mainSections .Section) .Params.comments }}

       {{ if .Site.Params.enableWaline }}
           {{ partial "comments.html" . }}
       {{ end }}

    {{ end }}
    {{ end }}

config里enable之后还是无法显示评论区。

**Comment by xioyito** [comment]
按照图片里进行操作, 图一参考了https://waline.js.org/guide/get-started/#html-%E5%BC%95%E5%85%A5-%E5%AE%A2%E6%88%B7%E7%AB%AF, 因为原valine的容器很窄, 完成后样式可能会出问题, 建议把waline容器放到正文下方.
![Snipaste_2024-03-14_23-12-30](https://github.com/xioyito/NewBee/assets/59784211/279eb415-9b99-4581-bd3a-3f607a1504ae)
![Snipaste_2024-03-14_23-15-17](https://github.com/xioyito/NewBee/assets/59784211/7430670a-b2d5-4c23-bd02-6e92358fb0ca)
![Snipaste_2024-03-14_23-27-32](https://github.com/xioyito/NewBee/assets/59784211/6d525498-34b0-4c50-bda9-10248858d0a3)

**Comment by Bladeisme** [comment]
按照图上改了之后还是没显示waline T T，把waline放到正文下面的话是需要修改single.html吗？
另外修改应该不需要动主题文件夹？我是复制了NewBee的layouts文件夹到根目录下后进行修改的

**Comment by xioyito** [comment]
1. 没显示可以尝试ctrl+c关闭hugo服务器, 刷新一遍页面使其处于访问失败的状态, 然后hugo server再次启动服务器, 再刷新页面, 这时应该有效果了.
2. waline可放的位置如下图.
3. 可以
![Snipaste_2024-03-15_10-49-07](https://github.com/xioyito/NewBee/assets/59784211/92003ca4-87eb-4a9b-a55b-597b0743f1f4)

**Comment by Bladeisme** [comment]
谢谢！成功了！♥
最开始找了会儿放在哪，放到content-all.html这儿就出现了

**Comment by Bladeisme** [comment]
不好意思，又有新问题了！
想要修改css样式，先打算修改follow的background，把style.css复制到custom.css之后修改了顶部的primary颜色，提交之后发现follow按钮颜色确实改变了，但是dark/light模式切换失效，切换时背景没变，但图片会增加/去掉阴影，暂时撤回了这次修改。修改这个primary颜色的话是需要其他的一起修改吗？

**Comment by xioyito** [comment]
这里建议直接修改主题里的style.css, 可能还需要连同style-dark.css一同修改. 目前自定义颜色还有bug, 请待完善.

**Comment by Bladeisme** [comment]
css我样式我通过直接修改style.css和style-dark.css暂时解决了。
然后又有了一个新的问题，如果我要新增页面的话要怎么操作呢？不好意思问题很多OTL
目前是想通过artitalk增加一个说说页，实际上博客已经有这个页面了但打开来是空的，不知道是哪一步出错了。
config里[mamu.main]那里每一条下面的`pre=‘’`不知道指的是什么？新增了
```
[[menu.main]] 
    name = "碎碎念"
    url = "/artitalk"
    weight = 6  
```
然后打开博客发现目录里确实有出现，页面主体是正常的但没有发说说的按钮。不过也可能是我leancloud配置错误……
