### ISSUE TITLE
列表页面卡片右下角挂件上面的竖线在封面图片是透明背景PNG格式的情况下会显示出来

### ISSUE THREAD

**Issue by scmiot** [xioyito/NewBee#4]
列表页面卡片右下角挂件上面的竖线在封面图片是透明背景PNG格式的情况下会显示出来。
![截图 2022-07-12 11-32-53](https://user-images.githubusercontent.com/91941652/178403186-a528f9ab-c5fc-4256-bef7-d9e855255786.png)

**Comment by xioyito** [comment]
ok，明白




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xioyito/NewBee"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 中午11:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xioyito/NewBee] 列表页面卡片右下角挂件上面的竖线在封面图片是透明背景PNG格式的情况下会显示出来 (Issue #4)





 
列表页面卡片右下角挂件上面的竖线在封面图片是透明背景PNG格式的情况下会显示出来。

**Comment by xioyito** [comment]
@scmiot ，已修复

**Comment by scmiot** [comment]
已确认修复。
