### ISSUE TITLE
Not sure where to create new posts.

### ISSUE THREAD

**Issue by nnagle123** [xioyito/NewBee#6]
Hey man, awesome theme!  I just can't seem to create a new post. I followed the instructions in the read me, but when I got to the :

hugo new "posts/first-post.md"  

I was receiving an error on my windows machine.  I think because there's no "posts" directory by default.  So I created one.  That didn't work.  More errors.  So I tried creating the "posts" directory in a new directory called "en."  I played around with the file path for a while, but couldn't seem to create a post.  I tried again from my linux machine and was able to create the post, but the website couldn't seem to find the post I created in the browser.  

Not sure if something in the config file needs to be changed?   Any help would be awesome.  

Thanks again.

**Comment by xioyito** [comment]
@nnagle123 Re-download the theme file and then follow the readme again, I have fixed this bug caused multilingual support. So far, you can use it without language problem if you use english. For multilingual, I'll write a post about it later.
