### ISSUE TITLE
’#' follow a chinese character will be render as ’ #'

### ISSUE THREAD

**Issue by jackyzjk** [xioyito/NewBee#8]
`’#'` follow a chinese character will be render as `’ #'`
for example: `固定值’#'` -> `固定值’ #'`

**Comment by xioyito** [comment]
@jackyzjk try to add '\' before a special character

**Comment by xioyito** [comment]
@jackyzjk try to add '\' before a special character

**Comment by jackyzjk** [comment]
It's OK, thanks you!
