### ISSUE TITLE
第一次访问太慢了

### ISSUE THREAD

**Issue by jackyzjk** [xioyito/NewBee#9]
第一次访问时屏幕中间总会出现个加载条<img width="229" alt="load" src="https://user-images.githubusercontent.com/15801667/198047278-21ce67ab-b21e-4706-b63b-0e0bb48bddd1.png">，要加载好几秒才能彻底打开网页，这个能否优化一下，我看[你的网站](https://xioyito.top/zh/)也是这样的。

**Comment by xioyito** [comment]
@jackyzjk 已修复，如果还慢应该是网络问题

**Comment by jackyzjk** [comment]
It's OK, thanks!
